name: Doctest
on: [push]
jobs:
  test_readme_and_sphinx_docs:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build myfm
        run: |
          pip install --upgrade pip
          pip install numpy scipy pandas scikit-learn
          pip install .
          curl http://files.grouplens.org/datasets/movielens/ml-100k.zip -o ~/.ml-100k.zip
      - name: Run pytest
        run: |
          pip install pytest phmdoctest sphinx==4.4.0 sphinx_rtd_theme
      - name: Test Readme.md
        run: |
          GEN_TEST_FILE=phmdoctest_out.py
          phmdoctest README.md --outfile "$GEN_TEST_FILE"
          pytest "$GEN_TEST_FILE"
          rm "$GEN_TEST_FILE"
      - name: Run sphinx doctest
        run: |
          cd doc
          make doctest
