name: Test & Upload coverage
on: [push]
jobs:
  run_pytest_upload_coverage:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build myfm & test
        run: |
          sudo apt-get install lcov
          pip install --upgrade pip
          pip install scikit-build setuptools-scm pytest pytest-cov pytest-mock nanobind
          FLAGS="-fprofile-arcs -ftest-coverage"
          CFLAGS="$FLAGS" CXXFLAGS="$FLAGS" pip install --editable .
          pytest --cov=./src/myfm tests/
          coverage xml
          lcov -d `pwd` -c -o coverage.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml,./coverage.info
          verbose: false
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
